//
#pragma once

#define NO_DEBUG
#define NO_PRINT

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 30
#define MOUSEKEY_TIME_TO_MAX 40
#define MOUSEKEY_FRICTION 1
#define MOUSEKEY_MOVE_DELTA 1
