//
#pragma once

#define NO_DEBUG
#define NO_PRINT

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 100
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 32
#define MOUSEKEY_TIME_TO_MAX 30
#define MOUSEKEY_FRICTION 20
#define MOUSEKEY_MOVE_DELTA 1
